import { backgroundImage, PageLayout } from "@dex-web/ui";
import localFont from "next/font/local";
import "../lib/orpc.server";
import Providers from "./_components/Providers";
import "./global.css";
import { NextIntlClientProvider } from "next-intl";
import { AppFooter } from "./_components/AppFooter";
import { AppHeader } from "./_components/AppHeader";

const bitsumishiRegular = localFont({
  src: "./_fonts/bitsumishi-regular.woff2",
  style: "normal",
  variable: "--font-bitsumishi-regular",
  weight: "400",
});

const classicConsoleNeue = localFont({
  src: "./_fonts/classic-console-neue.woff2",
  style: "normal",
  variable: "--font-classic-console-neue",
  weight: "400",
});

export const metadata = {
  description: "Generated by create-nx-workspace",
  title: "Welcome to web",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
			<html
				className={`${bitsumishiRegular.variable} ${classicConsoleNeue.variable} font-sans antialiased`}
				lang="en"
			>
				<body>
					<NextIntlClientProvider>
						<Providers>
							<PageLayout
								backgroundImageUrl={backgroundImage.src}
								footer={<AppFooter />}
								header={<AppHeader />}
							>
								{children}
							</PageLayout>
							{modal}
						</Providers>
					</NextIntlClientProvider>
				</body>
			</html>
		);
}
