export const CACHE_CONFIG = {
  POOLS_TTL: 5000,
  SEARCH_TTL: 300000,
  TOKENS_TTL: 60000,
} as const;
export const RATE_LIMIT_CONFIG = {
  DEFAULT_MAX_REQUESTS: 100,
  DEFAULT_WINDOW_MS: 60000,
  LIQUIDITY_MAX_REQUESTS: 10,
  LIQUIDITY_WINDOW_MS: 60000,
  POOLS_MAX_REQUESTS: 50,
  POOLS_WINDOW_MS: 60000,
  TOKENS_MAX_REQUESTS: 100,
  TOKENS_WINDOW_MS: 60000,
} as const;
export const VALIDATION_CONFIG = {
  MAX_AMOUNT: 2n ** 64n - 1n,
  MAX_POOLS_LIMIT: 1000,
  MAX_QUERY_LENGTH: 100,
  MAX_SEARCH_LENGTH: 50,
  MAX_TOKENS_LIMIT: 100,
  MIN_AMOUNT: 1n,
} as const;
export const TRANSACTION_CONFIG = {
  MAX_RETRY_ATTEMPTS: 15,
  RETRY_DELAY_MS: 2000,
  TIMEOUT_MS: 30000,
} as const;
export const LOGGING_CONFIG = {
  ERROR_SAMPLE_RATE: 0.1,
  PERFORMANCE_THRESHOLD_MS: 1000,
} as const;
