import { backgroundImage, PageLayout } from "@dex-web/ui";
import localFont from "next/font/local";
import "../../lib/orpc.server";
import "../global.css";
const bitsumishiRegular = localFont({
  src: "../bitsumishi-regular.woff2",
  style: "normal",
  variable: "--font-bitsumishi-regular",
  weight: "400",
});

import { NextIntlClientProvider } from "next-intl";
import { AppFooter } from "../../components/AppFooter";
import { AppHeader } from "../../components/AppHeader";

const classicConsoleNeue = localFont({
  src: "../classic-console-neue.woff2",
  style: "normal",
  variable: "--font-classic-console-neue",
  weight: "400",
});

export const metadata = {
  description: "Generated by create-nx-workspace",
  title: "Welcome to web",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  return (
    <html
      className={`${bitsumishiRegular.variable} ${classicConsoleNeue.variable} font-sans`}
      lang={locale}
    >
      <body>
        <NextIntlClientProvider>
          <PageLayout
            backgroundImageUrl={backgroundImage.src}
            footer={<AppFooter />}
            header={<AppHeader />}
          >
            {children}
          </PageLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
