import { create } from "@storybook/theming";

export const darklakeTheme = create({
  appBg: "#041C0F",
  appBorderColor: "#35D688",
  appBorderRadius: 4,
  appContentBg: "#062916",
  appPreviewBg: "#062916",
  barBg: "#09351D",
  barHoverColor: "#09351D",
  barSelectedColor: "#1A9A56",
  barTextColor: "#1A9A56",
  base: "dark",
  brandImage: "https://darklake.fi/images/logo-h-darklake-beta.svg",
  brandTarget: "_self",
  brandTitle: "Darklake Storybook",
  brandUrl: "https://darklake.fi",
  colorPrimary: "#09351D",
  colorSecondary: "#4A63D2",
  inputBg: "#09351D",
  inputBorder: "#35D688",
  inputBorderRadius: 2,
  inputTextColor: "#1A9A56",
  textColor: "#2CFF8E",
  textInverseColor: "#09351D",
});
